/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/Dashboard/index'
import { Route as DashboardAccountsAccNoRouteImport } from './routes/Dashboard/Accounts/$AccNo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/Dashboard/',
  path: '/Dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAccountsAccNoRoute = DashboardAccountsAccNoRouteImport.update({
  id: '/Dashboard/Accounts/$AccNo',
  path: '/Dashboard/Accounts/$AccNo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardIndexRoute
  '/Dashboard/Accounts/$AccNo': typeof DashboardAccountsAccNoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardIndexRoute
  '/Dashboard/Accounts/$AccNo': typeof DashboardAccountsAccNoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Dashboard/': typeof DashboardIndexRoute
  '/Dashboard/Accounts/$AccNo': typeof DashboardAccountsAccNoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Dashboard' | '/Dashboard/Accounts/$AccNo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Dashboard' | '/Dashboard/Accounts/$AccNo'
  id: '__root__' | '/' | '/Dashboard/' | '/Dashboard/Accounts/$AccNo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountsAccNoRoute: typeof DashboardAccountsAccNoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/': {
      id: '/Dashboard/'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/Accounts/$AccNo': {
      id: '/Dashboard/Accounts/$AccNo'
      path: '/Dashboard/Accounts/$AccNo'
      fullPath: '/Dashboard/Accounts/$AccNo'
      preLoaderRoute: typeof DashboardAccountsAccNoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountsAccNoRoute: DashboardAccountsAccNoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
